<?php
$_order = $block->getOrder();
$_store = $block->getStore();
$_invoice = $block->getInvoice();

?><b>Order: #<?= $_order->getIncrementId(); ?></b>
<?php if ($block->getInvoiceIncrementId()) { echo '<br>Invoice: #'.$block->getInvoiceIncrementId().'</br>'; } ?><br>
<br>
<b><?= __('Shipping method'); ?>:</b> <?= $_order->getShippingDescription(); ?><br>
<br>
<b><?= __('Billing address'); ?></b><br>
<?= nl2br(preg_replace("/\n\n+/s", "\n", strip_tags($block->getAddressHTML('billing')))); ?>
<br>
<b><?= __('Shipping address'); ?></b><br>
<?= nl2br(preg_replace("/\n\n+/s", "\n", strip_tags($block->getAddressHTML('shipping')))); ?>
<br>
<table><thead><tr><td><b><?= __('Product'); ?></b>&nbsp;</td><td>_</td><td>&nbsp;<b><?= __('SKU'); ?></b>&nbsp;</td><td>_</td><td>&nbsp;<b><?= __('Price'); ?></b>&nbsp;</td><td>_</td><td>&nbsp;<b><?= __('Qty'); ?></b>&nbsp;</td><td>_</td><td>&nbsp;<b><?= __('Subtotal'); ?></b>&nbsp;</td></tr></thead><tbody><?php foreach ($block->getOrderItems() as $item) { echo $block->getItemHtml($item); } ?></tbody><tfoot><?= $block->getTotalsHtml(); ?></tfoot></table>
