<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $_order  = $block->getOrder();
    $_source = $block->getSource();
?>
<?php if ($_source->getCustomerBalanceAmount()): ?>
<tr>
    <td>
        <?= /* @escapeNotVerified */ __('Store Credit') ?>
    </td>
    <td><span>-<?= /* @escapeNotVerified */ strip_tags($_order->formatPrice($_source->getCustomerBalanceAmount())) ?></span></td>
</tr>
<?php endif; ?>
