<?php
$_order = $block->getOrder();
$_store = $block->getStore();
$_invoice = $block->getInvoice();


?><?php if ($block->getInvoiceIncrementId()) { echo '<h1>Invoice: #'.$block->getInvoiceIncrementId().'</h1>'; } else { ?><h1>Order: #<?= $_order->getIncrementId(); ?></h1><?php } ?><table class="table table-bordered"><thead><tr><td colspan="2"><b><?= __('Order Details'); ?></b></td></tr></thead><tbody><tr><td style="width: 50%;"><address><strong><?= $block->getStoreName(); ?></strong></address><?php if ($block->getStorePhone()) { ?><b><?= __('Phone'); ?>:</b> <?= $block->getStorePhone(); ?><br><?php } ?>
<b><?= __('Email'); ?>:</b> <?= $block->getStoreEmail(); ?><br>
<b><?= __('Website'); ?>:</b> <a href="<?= $block->getStoreUrl(); ?>"><?= $block->getStoreUrl(); ?></a></td>
<td style="width: 50%;"><b><?= __('Date added'); ?>:</b> <?= date('m/d/Y'); ?><br>
<b><?= __('Order Id'); ?>:</b> <?= $_order->getIncrementId(); ?><br>
<b><?= __('Payment method'); ?>:</b> <?= $_order->getPayment()->getMethodInstance()->getCode(); ?><br>
<b><?= __('Shipping method'); ?>:</b> <?= $_order->getShippingDescription(); ?><br>
</tr></tbody></table><table class="table table-bordered"><thead><tr><td style="width:50%;"><b><?= __('Billing address'); ?></b></td><td style="width:50%;"><b><?= __('Shipping address'); ?></b></td>
</tr></thead><tbody><tr><td><address><?= $block->getAddressHtml('billing'); ?></address></td><td><address><?= $block->getAddressHtml('shipping'); ?></address></td></tr></tbody>
</table><table class="table table-bordered"><thead><tr><td><b><?= __('Product'); ?></b></td><td><b><?= __('SKU'); ?></b></td><td class="text-right"><b><?= __('Price'); ?></b></td><td class="text-right"><b><?= __('Qty'); ?></b></td><td class="text-right"><b><?= __('Subtotal'); ?></b></td></tr></thead><tbody><?php foreach ($block->getOrderItems() as $item) { echo $block->getItemHtml($item); } ?></tbody><tfoot><?= $block->getTotalsHtml(); ?></tfoot></table>
