<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Tax\Block\Item\Price\Renderer */

$_item = $block->getItem();
?><?php if (($block->displayPriceInclTax() || $block->displayBothPrices()) && !$_item->getNoSubtotal()): ?><span class="cart-price"><?= /* @escapeNotVerified */ $block->formatPrice($_item->getRowTotalInclTax()) ?></span><?php endif; ?><?php if (($block->displayPriceExclTax() || $block->displayBothPrices()) && !$_item->getNoSubtotal()): ?><span><span class="cart-price"><?= /* @escapeNotVerified */ $block->formatPrice($_item->getRowTotal()) ?></span></span><?php endif; ?>